### ISSUE TITLE
Show attached images inline

### ISSUE THREAD

**Issue by chazeah** [eranrund/lightr#1]
Right now, when an email contains file attachments, they appear at the bottom as such:
![image](https://cloud.githubusercontent.com/assets/899450/16092593/5968037e-32ed-11e6-946b-033507f170f2.png)
example: https://github.com/FundersClub/FundersClub/issues/6452

For attachments that are images (png, jpg, gif, svg?) can we also start inlining them? Save us a click/makes the click target bigger, e.g.:
```
---
*Attachments:*

1. [Capture.PNG](https://lightr-fire-media.s3.amazonaws.com/mailbox_attachments/2016/06/14/XXX.PNG)
  ![](https://lightr-fire-media.s3.amazonaws.com/mailbox_attachments/2016/06/14/XXX.PNG)

```
(Note: including an additional newline after the `*Attachments:*` line, and then indent the `![](...)` by two spaces. This will result in it rendering as a markdown list.)

**Comment by eranrund** [comment]
Done
